version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=timecoder
    volumes:
    - "./mycustom.cnf:/etc/mysql/conf.d/custom.cnf"
  timecoder-api:
    image: spirogov/timecoder:1.1
    container_name: timecoder
    depends_on:
    - mysql
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    links:
    - mysql
    ports:
      - 8080:8080
      - 36320:36320

