version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=timecoder
  postgresql:
    image: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

volumes:
  db-data: