version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
    - 3306:3306
    expose:
    - 3306
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=timecoder
    volumes:
    - "./mycustom.cnf:/etc/mysql/conf.d/custom.cnf"
  timecoder-api:
    image: spirogov/timecoder:1.3
    container_name: timecoder
    depends_on:
    - mysql
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    links:
    - mysql
  ui:
    image: spirogov/timecoder-ui:1.3
    container_name: timecoder-ui
    ports:
    - 80:80
    links:
    - timecoder-api
  gateway:
    image: spirogov/timecoder-gateway:latest
    container_name: timecoder-gateway
    ports:
    - 8086:8080
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    links:
    - timecoder-api