version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
    - 3306:3306
    expose:
    - 3306
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=timecoder
    volumes:
    - "./mycustom.cnf:/etc/mysql/conf.d/custom.cnf"
  timecoder-api:
    image: spirogov/timecoder:0.1.0
    container_name: timecoder
    depends_on:
    - mysql
    ports:
    - 8086:8080
    environment:
    - DATABASE_HOST=mysql
    - DATABASE_NAME=timecoder
    - DATABASE_USER=root
    - MYSQL_ROOT_PASSWORD=admin
    - DATABASE_PORT=3306
    - SPRING_PROFILES_ACTIVE=prod
    links:
    - mysql
  ui:
    image: spirogov/timecoder-ui:0.1.7
    container_name: timecoder-ui
    ports:
    - 8088:4200
    links:
    - timecoder-api