spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/timecoder?useUnicode=yes&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

---
spring:
  profiles: prod
  datasource:
    username: ${USER_NAME}
    password: ${PASSWORD}
    url: jdbc:mysql://mysql:3306/timecoder?useUnicode=yes&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql