spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/timecoder
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

---
spring:
  profiles: prod
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/timecoder
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update